export enum IconSize {
	SMALL = 14,
	DEFAULT = 17,
	BIG = 24,
	XL = 32,
	XXL = 45
}

export enum IconType {
	SEARCH = 'search',
	CLOSE = 'close',
	PLUS = 'plus',
	MINUS = 'minus',
	TRUCK = 'truck',
	PHONE = 'phone',
	ORDER_DEFAULT = 'order-default',
	ORDER_PENDING = 'order-pending',
	ORDER_FINISHED = 'order-finished',
	ORDER_PICKED_UP = 'order-picked-up',
	ORDER_QUOTE = 'order-quote',
	QR = 'qr',
	EDIT = 'edit',
	USER = 'user',
	USER_PLUS = 'user-plus',
	COINS = 'coins',
	WHATSAPP = 'whatsapp',
	LOCATION = 'location',
	CLOCK = 'clock',
	LINK = 'link',
	EYE = 'eye',
	TRASH = 'trash',
	CART = 'cart',
	SENT = 'sent',
	LIST = 'list',
	DOWN = 'down',
	PRINTER = 'printer',
	NOT_DONE = 'not-done',
	DONE = 'done',
	VIDEO = 'video',
	DOWNLOAD = 'download',
	RULER = 'ruler',
	QUESTION = 'question',
	FORM = 'form',
	HOME = 'home',
	SETTINGS = 'settings',
	LOGOUT = 'logout',
	MOLD = 'mold',
	EXCEL = 'excel',
	COPY = 'copy',
	CAMERA = 'camera',
	ALERT = 'alert',
	LEFT = 'left',
	RIGHT = 'right',
	LOGO = 'logo',
	LOADING = 'loading'
}
